name: Scherbakov_django deployment
  on: [push, pull_request]
  jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
  - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pep8-naming flake8-broken-line flake8-return
        pip install -r requirements.txt
  - name: Test with flake8 and django tests
        run: |
          # запуск проверки проекта по flake8
          python -m flake8
          # запустить написанные разработчиком тесты
#          pytest
  deploy:
    runs-on: centos-latest
#    needs: build_and_push_to_docker_hub
    steps:
      - name: executing remote ssh commands to deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}
#          passphrase: ${{ secrets.PASSPHRASE }}
          script: |
#            sudo docker pull fulgrim1983/sprint_19:latest
#            sudo docker-compose stop
#            sudo docker-compose rm dgritsay_web_1
#            sudo docker-compose up -d
